apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-deployment
  labels:
    app: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: the-project-container
        image: reno09/the_project:latest